version: '3.4'

services:
  api:
    build:
      context: .
      args:
        AWS_ACCESS_KEY_ID:
        AWS_SECRET_ACCESS_KEY:
    restart: always
    environment:
      NUMBER_OF_PROCESSES: 4
    ports:
      - "8000:8000"
      - "4000:4000"